### ISSUE TITLE
删掉了sample.tex, 改用pandoc处理对应的md? 

### ISSUE THREAD

**Issue by logithm** [kalxd/morelull#1]
求保留sample.tex, 平时基本上用不到pandoc.

**Comment by kalxd** [comment]
难得会有人喜欢，欣喜若狂。

sample.tex太旧了，改成[文档](https://github.com/kalxd/morelull/blob/master/doc.md)。命令和环境名称都使用双拼（小鹤双拼）。

如若觉得这个模板可用，可以改成正常的名字。
